# GdUnitTestSuite
extends GdUnitTestSuite

## The walkthrough is written by this suite, from the others (ADR-031).
##
## QM's walkthrough record makes one demand of every repository: one
## `walkthrough/` at the root, executed by the ordinary test command, so that
## the documentation a newcomer reads is the thing that ran. In a Python
## repository the pages are doctests. In a Godot one the examples are not text
## -- a drag, a frame, a ball in flight -- so the record's other mode applies:
## the tests emit the documentation, and the generator asserts its artifacts
## exist. This suite is that generator, and it is a test suite rather than a
## script because that is what makes regeneration ride the command people
## already run. Drift then arrives as an uncommitted diff in `git status`,
## which nobody can miss, rather than as a page nobody re-read.
##
## What it writes, every run, from `registry.gd`:
##
## - `walkthrough/NN-<id>.md`, one per suite: the suite's own header as prose,
##   then every test's name as a sentence linking to the line it is asserted
##   on, then the pictures the suite's tests recorded.
## - `walkthrough/README.md`, the index.
##
## What it checks: every suite under `tests/` has a page and every page has a
## suite; every picture the registry declares was recorded and every picture
## recorded is declared; every command the hand-written first page tells a
## reader to run is one this tree has; every picture the README or a document
## under `docs/` embeds is one the registry names. The page a reader reads is
## the page that ran, and its links are the assertions.
##
## Nothing here counts anything into a page. A number that changes with every
## run is a diff on every run, and the pages are meant to change only when a
## behaviour does.

const Registry := preload("res://tests/walkthrough/registry.gd")

const ROOT := "res://walkthrough"
## Written by hand, checked by `test_every_command_the_first_page_names_exists`.
const FIRST_PAGE := "01-getting-it-running.md"
const MARKER_PREFIX := "<!-- Generated by tests/walkthrough/test_walkthrough.gd from "
const MARKER_SUFFIX := ". Do not edit this file: edit the suite, run the tests, commit what they wrote. -->"

var _test_line := RegEx.create_from_string("^func (test_[A-Za-z0-9_]+)\\s*\\(")
var _fence := RegEx.create_from_string("(?s)```[^\\n]*\\n(.*?)```")
var _res_path := RegEx.create_from_string("res://[A-Za-z0-9_./-]+")
var _python_tool := RegEx.create_from_string("python (tools/[A-Za-z0-9_]+\\.py)")
var _build_target := RegEx.create_from_string("^if wants ([a-z0-9-]+)")
var _embedded_shot := RegEx.create_from_string("(?:[.][.]/)?(?:walkthrough/)?shots/([A-Za-z0-9-]+)/([A-Za-z0-9-]+)[.]png")

## The hand-written documents that may embed a walkthrough picture. A picture
## surfaced in the README is a picture the README can be wrong about, so the
## suite checks the name it uses is one the registry declares.
const DOCS_THAT_EMBED := ["res://README.md", "res://walkthrough/" + FIRST_PAGE]


# ------------------------------------------------------------- the checks ----

func test_every_suite_under_tests_is_a_page_and_every_page_is_a_suite() -> void:
	var on_disk := _suites_under("res://tests")
	on_disk.sort()
	var listed: Array[String] = []
	var ids := {}
	for page in Registry.PAGES:
		listed.append(page["suite"])
		assert_bool(ids.has(page["id"])) \
			.override_failure_message("two registry rows share the id %s" % page["id"]) \
			.is_false()
		ids[page["id"]] = true
	listed.sort()
	for suite in on_disk:
		assert_bool(listed.has(suite)) \
			.override_failure_message(
				"%s has no page: add a row for it to tests/walkthrough/registry.gd, " % suite +
				"in the place a newcomer should meet it") \
			.is_true()
	for suite in listed:
		assert_bool(FileAccess.file_exists(suite)) \
			.override_failure_message(
				"tests/walkthrough/registry.gd lists %s, which is not in the tree" % suite) \
			.is_true()


func test_the_pages_are_written_from_the_suites() -> void:
	var written: Array[String] = []
	var ordinal := 2  # 01 is the hand-written page
	for page in Registry.PAGES:
		var name := "%02d-%s.md" % [ordinal, page["id"]]
		_write("%s/%s" % [ROOT, name], _render_page(ordinal, page))
		written.append(name)
		ordinal += 1
	_write("%s/README.md" % ROOT, _render_index())
	written.append("README.md")

	# A page whose row was removed is deleted, not left to say something the
	# suite no longer says. Only pages carrying the marker: the hand-written
	# first page is never touched.
	for name in DirAccess.get_files_at(ROOT):
		if not name.ends_with(".md") or written.has(name):
			continue
		if _first_line("%s/%s" % [ROOT, name]).begins_with(MARKER_PREFIX):
			DirAccess.remove_absolute(ProjectSettings.globalize_path("%s/%s" % [ROOT, name]))

	for name in written:
		var path := "%s/%s" % [ROOT, name]
		assert_bool(FileAccess.file_exists(path)).override_failure_message("%s was not written" % path).is_true()
		assert_str(_first_line(path)).starts_with(MARKER_PREFIX)
	assert_bool(FileAccess.file_exists("%s/%s" % [ROOT, FIRST_PAGE])) \
		.override_failure_message("the hand-written first page %s is missing" % FIRST_PAGE) \
		.is_true()


func test_every_declared_shot_is_recorded_and_every_recorded_shot_is_declared() -> void:
	# The pictures are not in the repository, so on a headless run there is
	# nothing to find and nothing to conclude from not finding it. The run
	# that can record is the run that is held to it: locally with a window,
	# and CI's walkthrough job under xvfb, which deletes them all first.
	var could_record := DisplayServer.get_name() != "headless"
	var declared := {}
	for page in Registry.PAGES:
		for shot in page["shots"]:
			var path := "%s/shots/%s/%s.png" % [ROOT, page["id"], shot]
			declared[path] = true
			if could_record:
				assert_bool(FileAccess.file_exists(path)) \
					.override_failure_message(
						"%s is declared in the registry and this run, which had a display, did not record it. " % path +
						"A test in %s must `await Walkthrough.capture(self, \"%s\", \"%s\")`." % [page["suite"], page["id"], shot]) \
					.is_true()
	var shots_dir := "%s/shots" % ROOT
	if not DirAccess.dir_exists_absolute(ProjectSettings.globalize_path(shots_dir)):
		return
	for id in DirAccess.get_directories_at(shots_dir):
		for file in DirAccess.get_files_at("%s/%s" % [shots_dir, id]):
			var path := "%s/%s/%s" % [shots_dir, id, file]
			assert_bool(declared.has(path)) \
				.override_failure_message(
					"%s was recorded but no registry row declares it; a picture " % path +
					"nobody asked for is a picture nobody will notice going stale") \
				.is_true()


func test_every_command_the_first_page_names_exists() -> void:
	var text := FileAccess.get_file_as_string("%s/%s" % [ROOT, FIRST_PAGE])
	assert_str(text).is_not_empty()
	var targets := _build_targets()
	var claims := 0
	for block in _fence.search_all(text):
		for raw in block.get_string(1).split("\n"):
			var line := raw.strip_edges().trim_prefix("$ ")
			if line.is_empty() or line.begins_with("#"):
				continue
			if line.begins_with("tools/build.sh"):
				for target in line.split(" ", false).slice(1):
					if target.begins_with("#"):
						break
					claims += 1
					assert_bool(targets.has(target)) \
						.override_failure_message(
							"%s tells a reader to run `tools/build.sh %s`, and build.sh has no target %s (it has: %s)"
							% [FIRST_PAGE, target, target, ", ".join(targets)]) \
						.is_true()
			for m in _python_tool.search_all(line):
				claims += 1
				assert_bool(FileAccess.file_exists("res://" + m.get_string(1))) \
					.override_failure_message("%s names %s, which is not in the tree" % [FIRST_PAGE, m.get_string(1)]) \
					.is_true()
			for m in _res_path.search_all(line):
				claims += 1
				var path := m.get_string(0).rstrip(".,")
				assert_bool(FileAccess.file_exists(path) or DirAccess.dir_exists_absolute(ProjectSettings.globalize_path(path))) \
					.override_failure_message("%s names %s, which is not in the tree" % [FIRST_PAGE, path]) \
					.is_true()
			if line.begins_with("./addons/gdUnit4/runtest.sh"):
				claims += 1
				assert_bool(FileAccess.file_exists("res://addons/gdUnit4/runtest.sh")).is_true()
	# A first page that names nothing runnable is not a first page.
	assert_int(claims).is_greater(0)


func test_every_picture_the_documents_embed_is_one_the_suite_recorded() -> void:
	var declared := {}
	for page in Registry.PAGES:
		for shot in page["shots"]:
			declared["%s/%s" % [page["id"], shot]] = true
	var docs: Array[String] = []
	docs.append_array(DOCS_THAT_EMBED)
	for name in DirAccess.get_files_at("res://docs"):
		if name.ends_with(".md"):
			docs.append("res://docs/%s" % name)
	for doc in docs:
		for m in _embedded_shot.search_all(FileAccess.get_file_as_string(doc)):
			var key := "%s/%s" % [m.get_string(1), m.get_string(2)]
			var where := doc.trim_prefix("res://")
			assert_bool(declared.has(key)) 				.override_failure_message(
					"%s embeds walkthrough/shots/%s.png, which no registry row declares; " % [where, key] +
					"a picture the documents show has to be one a test records") 				.is_true()
			# Not in the repository, so only a run that could have recorded it
			# is held to its being there.
			if DisplayServer.get_name() != "headless":
				assert_bool(FileAccess.file_exists("res://walkthrough/shots/%s.png" % key)) 					.override_failure_message(
						"%s embeds walkthrough/shots/%s.png, which this run did not record" % [where, key]) 					.is_true()


# ----------------------------------------------------------- the rendering ---

func _render_page(ordinal: int, page: Dictionary) -> String:
	var suite: String = page["suite"]
	var rel := suite.trim_prefix("res://")
	var source := FileAccess.get_file_as_string(suite)
	var out := PackedStringArray()
	out.append(MARKER_PREFIX + rel + MARKER_SUFFIX)
	out.append("")
	out.append("# %02d — %s" % [ordinal, page["title"]])
	out.append("")
	out.append(("*Written by the suite from [`%s`](../%s). Every line under " +
		"**What the suite asserts** is the name of a test that runs on every pull " +
		"request, and its link is the assertion.*") % [rel, rel])
	out.append("")
	for line in _header_of(source):
		out.append(line)
	out.append("")
	out.append("## What the suite asserts")
	out.append("")
	for t in _tests_in(source):
		out.append("- [%s](../%s#L%d)" % [_sentence(t["name"]), rel, t["line"]])
	var shots: Dictionary = page["shots"]
	if not shots.is_empty():
		out.append("")
		out.append("## As recorded")
		out.append("")
		out.append("*Taken by the tests above, from the scene they asserted against, " +
			"by every run with a display. Not in the repository: run the suite with a " +
			"window and they appear here, or take CI's `walkthrough-shots` artifact. " +
			"Recorded, never compared (ADR-031).*")
		for shot in shots:
			out.append("")
			out.append("![%s](shots/%s/%s.png)" % [shots[shot], page["id"], shot])
			out.append("")
			out.append("*%s*" % shots[shot])
	out.append("")
	out.append("---")
	out.append("")
	out.append(_nav(ordinal))
	return "\n".join(out) + "\n"


func _render_index() -> String:
	var out := PackedStringArray()
	out.append(MARKER_PREFIX + "tests/walkthrough/registry.gd" + MARKER_SUFFIX)
	out.append("")
	out.append("# golfVs, by running it")
	out.append("")
	out.append("One path through the game, in the order a newcomer meets it. The first page " +
		"is written by hand and every command on it is checked against the tree. Every " +
		"page after it is written **by the test suite**, from the suite: its prose is the " +
		"suite's own header, each line under *what the suite asserts* is a test's name " +
		"linking to the assertion, and each picture was taken by one of those tests from " +
		"the scene it asserted against. A page here cannot say something the suite does " +
		"not, because the suite wrote it (ADR-031).")
	out.append("")
	out.append("1. [01 — Getting it running](%s)" % FIRST_PAGE)
	var ordinal := 2
	for page in Registry.PAGES:
		out.append("%d. [%02d — %s](%02d-%s.md)" % [ordinal, ordinal, page["title"], ordinal, page["id"]])
		ordinal += 1
	out.append("")
	out.append("## As recorded")
	out.append("")
	out.append("Every picture the walkthrough has, in page order. Each is taken by a test from " +
		"the scene it has just asserted against, by every run with a display; the " +
		"caption links to the page and the page links to the test. **The pictures are " +
		"not in the repository.** Run the suite with a window and they appear beside " +
		"these pages; CI's walkthrough job records them under a virtual display and " +
		"uploads them as the `walkthrough-shots` artifact.")
	ordinal = 2
	for page in Registry.PAGES:
		var shots: Dictionary = page["shots"]
		for shot in shots:
			out.append("")
			out.append("![%s](shots/%s/%s.png)" % [shots[shot], page["id"], shot])
			out.append("")
			out.append("*%s* — [%02d — %s](%02d-%s.md)" % [shots[shot], ordinal, page["title"], ordinal, page["id"]])
		ordinal += 1
	out.append("")
	out.append("## How it is kept true")
	out.append("")
	out.append("- **Regenerating is running the tests.** `tests/walkthrough/test_walkthrough.gd` " +
		"rewrites every generated page on every run of the suite; a page that changed " +
		"is a diff in `git status`, and it is committed with the change that caused it.")
	out.append("- **Pictures need a display, and are never committed.** A headless run draws " +
		"nothing; a run with a window -- the ordinary local run -- records every " +
		"declared picture under `walkthrough/shots/`, which is ignored by git. CI's " +
		"walkthrough job runs the suite under a virtual display, fails if any declared " +
		"picture was not recorded, and uploads what it took.")
	out.append("- **Drift is red.** CI runs the suite and then `git diff --exit-code -- walkthrough`: " +
		"a generated page that differs from the committed one fails the build.")
	out.append("- **The run that counts is on `main`.** A page that ran on a branch nobody merged " +
		"has not run; [the CI history for `main`]" +
		"(https://github.com/quaternionmedia/golfvs/actions/workflows/ci.yml?query=branch%3Amain) " +
		"is the evidence, not the presence of the workflow.")
	out.append("- **One registry.** `tests/walkthrough/registry.gd` is the only list: page order, " +
		"titles, which suite, which pictures. Every suite under `tests/` must have a row, " +
		"and every declared picture must be recorded, or the suite fails.")
	return "\n".join(out) + "\n"


func _nav(ordinal: int) -> String:
	var parts := PackedStringArray()
	if ordinal == 2:
		parts.append("← [01 — Getting it running](%s)" % FIRST_PAGE)
	else:
		var prev: Dictionary = Registry.PAGES[ordinal - 3]
		parts.append("← [%02d — %s](%02d-%s.md)" % [ordinal - 1, prev["title"], ordinal - 1, prev["id"]])
	parts.append("[Index](README.md)")
	if ordinal - 1 < Registry.PAGES.size():
		var next: Dictionary = Registry.PAGES[ordinal - 1]
		parts.append("[%02d — %s](%02d-%s.md) →" % [ordinal + 1, next["title"], ordinal + 1, next["id"]])
	return " · ".join(parts)


## The `##` block at the top of a suite, as prose: the explanation the suite
## already carries, which is the documentation, so it is not written twice.
func _header_of(source: String) -> PackedStringArray:
	var lines := PackedStringArray()
	var started := false
	for raw in source.split("\n"):
		var line := raw.strip_edges(false, true)
		if line.begins_with("##"):
			started = true
			lines.append(line.trim_prefix("##").trim_prefix(" "))
		elif started and not line.is_empty():
			break
	return lines


func _tests_in(source: String) -> Array[Dictionary]:
	var tests: Array[Dictionary] = []
	var number := 0
	for line in source.split("\n"):
		number += 1
		var m := _test_line.search(line)
		if m:
			tests.append({"name": m.get_string(1), "line": number})
	return tests


## `test_yaw_walks_around_the_focus` -> `Yaw walks around the focus`. The names
## are already sentences; this only takes the underscores out.
func _sentence(test_name: String) -> String:
	var words := test_name.trim_prefix("test_").replace("_", " ")
	return words.substr(0, 1).to_upper() + words.substr(1)


# ------------------------------------------------------------- the tree ------

func _suites_under(dir: String) -> Array[String]:
	var found: Array[String] = []
	for sub in DirAccess.get_directories_at(dir):
		found.append_array(_suites_under("%s/%s" % [dir, sub]))
	for file in DirAccess.get_files_at(dir):
		if file.begins_with("test_") and file.ends_with(".gd"):
			found.append("%s/%s" % [dir, file])
	return found


func _build_targets() -> PackedStringArray:
	var targets := PackedStringArray(["all"])
	for line in FileAccess.get_file_as_string("res://tools/build.sh").split("\n"):
		var m := _build_target.search(line)
		if m:
			targets.append(m.get_string(1))
	return targets


func _first_line(path: String) -> String:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return ""
	return file.get_line()


func _write(path: String, content: String) -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))
	var file := FileAccess.open(path, FileAccess.WRITE)
	assert(file != null, "walkthrough: could not open %s for writing" % path)
	file.store_string(content)
	file.close()
